version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: docker
    ports:
      - 8686:9876
    volumes:
      - ./app:/app
    tty: true
    # env_file:
      # - .env
    environment:
      PROJECT_ENV: docker
